config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  get 'pages/floorplans'

  get 'pages/contactus'

  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root "application#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  layout "application"
  
  def index
    #render html: "Hello Tonga"
  end
  
  def hello
    render html: "Hello WOrld!"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout 'tonga_layout'
  def home
  end

  def floorplans
  end

  def contactus
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/application/index.html.erb
<div class="container">
	<div class="jumbotron">
		<h1>Hello Tonga Apartments</h1>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TongaApartments</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/tonga_layout.html.erb
<!DOCTYPE html>
<style>
	.jumbo-header {
		position: relative;
		background-image: url(<%= asset_path('tonga-header-img.jpg') %>);
		background-repeat: no-repeat;
		background-size: cover;
		height: 300px;
	}
	.header-title {
		position: absolute;
		bottom: 10px;
		color: white;
	}
</style>
<html>
  <head>
    <title>Tonga Apartments LLC</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		<div class="container">
			
			<div class="jumbotron jumbo-header">
				<%= render 'navigation' %>
				<span class="header-title">
					<h1>Tonga Apartments LLC</h1>
				</span>
			</div>
		</div>
    <%= yield %>
  </body>
</html>

app/views/pages/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to "Home", pages_home_path %></li>
      <li><%= link_to "Contact Us", pages_contactus_path %></li>
      <li><%= link_to "Floor Plans", pages_floorplans_path %></li>
    </ul>
  </div>
</nav>

app/views/pages/contactus.html.erb
<h1>Pages#contactus</h1>
<p>Find me in app/views/pages/contactus.html.erb</p>

app/views/pages/floorplans.html.erb
<h1>Pages#floorplans</h1>
<p>Find me in app/views/pages/floorplans.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>